/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../../base';
// @ts-ignore
import { ErrorResponse } from '../../src/model';
// @ts-ignore
import { ResponseWithData } from '../../src/model';
// @ts-ignore
import { SearchCadet } from '../../src/model';
/**
 * SearchApi - axios parameter creator
 * @export
 */
export const SearchApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 검색된 카뎃 선택시 정보 파싱
         * @summary getSelectCadetInfo API
         * @param {SearchCadet} searchCadet 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSelectCadetInfo: async (searchCadet: SearchCadet, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'searchCadet' is not null or undefined
            assertParamExists('getSelectCadetInfo', 'searchCadet', searchCadet)
            const localVarPath = `/v3/search/select`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchCadet, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 멤버 검색 api
         * @summary search API
         * @param {string} begin begin 인자로 시작하는 이름
         * @param {} [UNKNOWN_PARAMETER_NAME] key in Token
         * @param {string} [iD] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search42UserResponse: async (begin: string, UNKNOWN_PARAMETER_NAME?: , iD?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'begin' is not null or undefined
            assertParamExists('search42UserResponse', 'begin', begin)
            const localVarPath = `/v3/search/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (begin !== undefined) {
                localVarQueryParameter['begin'] = begin;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SearchApi - functional programming interface
 * @export
 */
export const SearchApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SearchApiAxiosParamCreator(configuration)
    return {
        /**
         * 검색된 카뎃 선택시 정보 파싱
         * @summary getSelectCadetInfo API
         * @param {SearchCadet} searchCadet 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSelectCadetInfo(searchCadet: SearchCadet, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseWithData>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSelectCadetInfo(searchCadet, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 멤버 검색 api
         * @summary search API
         * @param {string} begin begin 인자로 시작하는 이름
         * @param {} [UNKNOWN_PARAMETER_NAME] key in Token
         * @param {string} [iD] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async search42UserResponse(begin: string, UNKNOWN_PARAMETER_NAME?: , iD?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseWithData>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.search42UserResponse(begin, UNKNOWN_PARAMETER_NAME, iD, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SearchApi - factory interface
 * @export
 */
export const SearchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SearchApiFp(configuration)
    return {
        /**
         * 검색된 카뎃 선택시 정보 파싱
         * @summary getSelectCadetInfo API
         * @param {SearchCadet} searchCadet 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSelectCadetInfo(searchCadet: SearchCadet, options?: any): AxiosPromise<ResponseWithData> {
            return localVarFp.getSelectCadetInfo(searchCadet, options).then((request) => request(axios, basePath));
        },
        /**
         * 멤버 검색 api
         * @summary search API
         * @param {string} begin begin 인자로 시작하는 이름
         * @param {} [UNKNOWN_PARAMETER_NAME] key in Token
         * @param {string} [iD] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search42UserResponse(begin: string, UNKNOWN_PARAMETER_NAME?: , iD?: string, options?: any): AxiosPromise<ResponseWithData> {
            return localVarFp.search42UserResponse(begin, UNKNOWN_PARAMETER_NAME, iD, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SearchApi - object-oriented interface
 * @export
 * @class SearchApi
 * @extends {BaseAPI}
 */
export class SearchApi extends BaseAPI {
    /**
     * 검색된 카뎃 선택시 정보 파싱
     * @summary getSelectCadetInfo API
     * @param {SearchCadet} searchCadet 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApi
     */
    public getSelectCadetInfo(searchCadet: SearchCadet, options?: AxiosRequestConfig) {
        return SearchApiFp(this.configuration).getSelectCadetInfo(searchCadet, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 멤버 검색 api
     * @summary search API
     * @param {string} begin begin 인자로 시작하는 이름
     * @param {} [UNKNOWN_PARAMETER_NAME] key in Token
     * @param {string} [iD] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApi
     */
    public search42UserResponse(begin: string, UNKNOWN_PARAMETER_NAME?: , iD?: string, options?: AxiosRequestConfig) {
        return SearchApiFp(this.configuration).search42UserResponse(begin, UNKNOWN_PARAMETER_NAME, iD, options).then((request) => request(this.axios, this.basePath));
    }
}

