/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContentDisposition
 */
export interface ContentDisposition {
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     */
    'filename'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     */
    'charset'?: string;
    /**
     * 
     * @type {number}
     * @memberof ContentDisposition
     * @deprecated
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     * @deprecated
     */
    'creationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     * @deprecated
     */
    'modificationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     * @deprecated
     */
    'readDate'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContentDisposition
     */
    'inline'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContentDisposition
     */
    'attachment'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContentDisposition
     */
    'formData'?: boolean;
}

