/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ErrorResponseHeadersHostAddress
 */
export interface ErrorResponseHeadersHostAddress {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'hostAddress'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'address'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'hostName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'linkLocalAddress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'multicastAddress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'anyLocalAddress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'loopbackAddress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'siteLocalAddress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'mcglobal'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'mcnodeLocal'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'mclinkLocal'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'mcsiteLocal'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'mcorgLocal'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'canonicalHostName'?: string;
}

