/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ErrorResponseHeadersContentLanguage
 */
export interface ErrorResponseHeadersContentLanguage {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'language'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'script'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'variant'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'country'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'unicodeLocaleAttributes'?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'unicodeLocaleKeys'?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'displayLanguage'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'displayScript'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'displayCountry'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'displayVariant'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'displayName'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'extensionKeys'?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'iso3Language'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersContentLanguage
     */
    'iso3Country'?: string;
}

