/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ErrorResponseHeaders } from './error-response-headers';
// May contain unused imports in some cases
// @ts-ignore
import { HttpStatusCode } from './http-status-code';
// May contain unused imports in some cases
// @ts-ignore
import { ProblemDetail } from './problem-detail';

/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {HttpStatusCode}
     * @memberof ErrorResponse
     */
    'statusCode'?: HttpStatusCode;
    /**
     * 
     * @type {Array<object>}
     * @memberof ErrorResponse
     */
    'detailMessageArguments'?: Array<object>;
    /**
     * 
     * @type {ProblemDetail}
     * @memberof ErrorResponse
     */
    'body'?: ProblemDetail;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'detailMessageCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'titleMessageCode'?: string;
    /**
     * 
     * @type {ErrorResponseHeaders}
     * @memberof ErrorResponse
     */
    'headers'?: ErrorResponseHeaders;
}

