/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ErrorResponseHeadersHostAddress } from './error-response-headers-host-address';

/**
 * 
 * @export
 * @interface ErrorResponseHeadersHost
 */
export interface ErrorResponseHeadersHost {
    /**
     * 
     * @type {ErrorResponseHeadersHostAddress}
     * @memberof ErrorResponseHeadersHost
     */
    'address'?: ErrorResponseHeadersHostAddress;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeadersHost
     */
    'port'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHost
     */
    'unresolved'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersHost
     */
    'hostName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersHost
     */
    'hostString'?: string;
}

