/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ContentDisposition } from './content-disposition';
// May contain unused imports in some cases
// @ts-ignore
import { ErrorResponseHeadersAcceptLanguageInner } from './error-response-headers-accept-language-inner';
// May contain unused imports in some cases
// @ts-ignore
import { ErrorResponseHeadersContentLanguage } from './error-response-headers-content-language';
// May contain unused imports in some cases
// @ts-ignore
import { ErrorResponseHeadersHost } from './error-response-headers-host';
// May contain unused imports in some cases
// @ts-ignore
import { MediaType } from './media-type';

/**
 * 
 * @export
 * @interface ErrorResponseHeaders
 */
export interface ErrorResponseHeaders {
    [key: string]: Array<string>;

    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeaders
     */
    'empty'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'location'?: string;
    /**
     * 
     * @type {ErrorResponseHeadersHost}
     * @memberof ErrorResponseHeaders
     */
    'host'?: ErrorResponseHeadersHost;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ErrorResponseHeaders
     */
    'all'?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'lastModified'?: number;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'contentLength'?: number;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'date'?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'origin'?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof ErrorResponseHeaders
     */
    'range'?: Array<object>;
    /**
     * 
     * @type {Set<object>}
     * @memberof ErrorResponseHeaders
     */
    'allow'?: Set<object>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'acceptCharset'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'cacheControl'?: string;
    /**
     * 
     * @type {ErrorResponseHeadersContentLanguage}
     * @memberof ErrorResponseHeaders
     */
    'contentLanguage'?: ErrorResponseHeadersContentLanguage;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'etag'?: string;
    /**
     * 
     * @type {ContentDisposition}
     * @memberof ErrorResponseHeaders
     */
    'contentDisposition'?: ContentDisposition;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'connection'?: Array<string>;
    /**
     * 
     * @type {Array<MediaType>}
     * @memberof ErrorResponseHeaders
     */
    'accept'?: Array<MediaType>;
    /**
     * 
     * @type {Array<ErrorResponseHeadersAcceptLanguageInner>}
     * @memberof ErrorResponseHeaders
     */
    'acceptLanguage'?: Array<ErrorResponseHeadersAcceptLanguageInner>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'basicAuth'?: string;
    /**
     * 
     * @type {Array<ErrorResponseHeadersContentLanguage>}
     * @memberof ErrorResponseHeaders
     */
    'acceptLanguageAsLocales'?: Array<ErrorResponseHeadersContentLanguage>;
    /**
     * 
     * @type {Array<MediaType>}
     * @memberof ErrorResponseHeaders
     */
    'acceptPatch'?: Array<MediaType>;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeaders
     */
    'accessControlAllowCredentials'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'accessControlAllowHeaders'?: Array<string>;
    /**
     * 
     * @type {Array<object>}
     * @memberof ErrorResponseHeaders
     */
    'accessControlAllowMethods'?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'accessControlAllowOrigin'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'accessControlExposeHeaders'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'accessControlMaxAge'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'accessControlRequestHeaders'?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof ErrorResponseHeaders
     */
    'accessControlRequestMethod'?: object;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'bearerAuth'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'expires'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'ifMatch'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'ifNoneMatch'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'ifUnmodifiedSince'?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'pragma'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'upgrade'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'vary'?: Array<string>;
    /**
     * 
     * @type {MediaType}
     * @memberof ErrorResponseHeaders
     */
    'contentType'?: MediaType;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'ifModifiedSince'?: number;
}

