/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HttpStatusCode
 */
export interface HttpStatusCode {
    /**
     * 
     * @type {boolean}
     * @memberof HttpStatusCode
     */
    'error'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HttpStatusCode
     */
    'is4xxClientError'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HttpStatusCode
     */
    'is5xxServerError'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HttpStatusCode
     */
    'is1xxInformational'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HttpStatusCode
     */
    'is2xxSuccessful'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HttpStatusCode
     */
    'is3xxRedirection'?: boolean;
}

