/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 위치 정보
 * @export
 * @interface Locate
 */
export interface Locate {
    /**
     * 서초, 개초 클러스터 상태
     * @type {string}
     * @memberof Locate
     */
    'planet'?: LocatePlanetEnum;
    /**
     * 층 정보
     * @type {number}
     * @memberof Locate
     */
    'floor'?: number;
    /**
     * 서초 클러스터
     * @type {number}
     * @memberof Locate
     */
    'cluster'?: number;
    /**
     * 자리정보
     * @type {string}
     * @memberof Locate
     */
    'spot'?: string;
}

export const LocatePlanetEnum = {
    _1: '1',
    _2: '2',
    _3: '3',
    _4: '4'
} as const;

export type LocatePlanetEnum = typeof LocatePlanetEnum[keyof typeof LocatePlanetEnum];


