/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MediaType
 */
export interface MediaType {
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    'subtype'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MediaType
     */
    'parameters'?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof MediaType
     */
    'qualityValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    'charset'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MediaType
     */
    'concrete'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MediaType
     */
    'wildcardType'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MediaType
     */
    'wildcardSubtype'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    'subtypeSuffix'?: string;
}

