/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Locate } from './locate';

/**
 * http response dto
 * @export
 * @interface SearchCadet
 */
export interface SearchCadet {
    /**
     * 카뎃의 이름
     * @type {string}
     * @memberof SearchCadet
     */
    'name'?: string;
    /**
     * 카뎃의 이미지
     * @type {string}
     * @memberof SearchCadet
     */
    'img'?: string;
    /**
     * 카뎃의 상태메시지
     * @type {string}
     * @memberof SearchCadet
     */
    'msg'?: string;
    /**
     * 
     * @type {Locate}
     * @memberof SearchCadet
     */
    'locate'?: Locate;
    /**
     * 카뎃의 상태
     * @type {number}
     * @memberof SearchCadet
     */
    'inOrOut'?: number;
    /**
     * 카뎃의 위치
     * @type {string}
     * @memberof SearchCadet
     */
    'location'?: string;
    /**
     * 평가
     * @type {number}
     * @memberof SearchCadet
     */
    'eval'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SearchCadet
     */
    'member'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SearchCadet
     */
    'friend'?: boolean;
}

