/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Image } from './image';

/**
 * 42seoul API에서 get한 카뎃 정보
 * @export
 * @interface Seoul42
 */
export interface Seoul42 {
    /**
     * IntraId
     * @type {string}
     * @memberof Seoul42
     */
    'login'?: string;
    /**
     * 맴버 클러스터 위치
     * @type {string}
     * @memberof Seoul42
     */
    'location'?: string;
    /**
     * 
     * @type {Image}
     * @memberof Seoul42
     */
    'image'?: Image;
    /**
     * 로그인한 클러스터 위치 서초 or 개포
     * @type {string}
     * @memberof Seoul42
     */
    'created_at'?: string;
    /**
     * 카뎃이 로그인해 있는지에 대한 상태
     * @type {boolean}
     * @memberof Seoul42
     */
    'active?'?: boolean;
}

