/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SessionExpiredExceptionCauseStackTraceInner
 */
export interface SessionExpiredExceptionCauseStackTraceInner {
    /**
     * 
     * @type {string}
     * @memberof SessionExpiredExceptionCauseStackTraceInner
     */
    'classLoaderName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionExpiredExceptionCauseStackTraceInner
     */
    'moduleName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionExpiredExceptionCauseStackTraceInner
     */
    'moduleVersion'?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionExpiredExceptionCauseStackTraceInner
     */
    'methodName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionExpiredExceptionCauseStackTraceInner
     */
    'fileName'?: string;
    /**
     * 
     * @type {number}
     * @memberof SessionExpiredExceptionCauseStackTraceInner
     */
    'lineNumber'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SessionExpiredExceptionCauseStackTraceInner
     */
    'nativeMethod'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SessionExpiredExceptionCauseStackTraceInner
     */
    'className'?: string;
}

